[LOCAL]
kafka.topic = sbdl_kafka_local
kafka.bootstrap.servers = localhost:9092
account.filter = active_ind = 1
hive.database =

[QA]
kafka.topic = sbdl_kafka_qa
kafka.bootstrap.servers = qa-kafka:9092
account.filter = active_ind = 1
hive.database = sbdl_qa_db

[PROD]
kafka.topic = sbdl_kafka_prod
kafka.bootstrap.servers = prod-kafka:9092
account.filter = active_ind = 1
hive.database = sbdl_prod_db
