[LOCAL]
spark.app.name = SBDL_Project
spark.master = local[*]

[QA]
spark.executor.instances = 4
spark.executor.cores = 2
spark.executor.memory = 4g

[PROD]
spark.executor.instances = 8
spark.executor.cores = 5
spark.executor.memory = 10g
